name: Ejecutar Hola Mundo en C#

on:
  push:
    branches:
      - main  # Se ejecutará cuando hagas push al branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Usa una máquina virtual Ubuntu en la nube

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3  # Clona tu código en la VM de GitHub Actions

      - name: Instalar SDK de .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Puedes cambiar por 8.0.x o 6.0.x si usas otra versión

      - name: Restaurar dependencias (opcional en este caso)
        run: dotnet restore

      - name: Compilar el proyecto
        run: dotnet build --configuration Release

      - name: Ejecutar la aplicación
        run: dotnet run --project .
